FROM jpetazzo/dind:latest

RUN apt-get install -y --no-install-recommends make python-pip && \
    pip install tutum && \
    mkdir /app

ADD haproxy /app/haproxy
ADD Dockerfile /app/Dockerfile
ADD integration_test.sh /app/integration_test.sh
ADD run-test.sh /app/run-test.sh
WORKDIR /app

CMD ["/app/run-test.sh"]

